server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root12345YH@
    url: jdbc:mysql://94.74.105.59:3306/test?characterEncoding=UTF-8&serverTimezone=UTC
  redis:
    host: 94.74.105.59
    port: 6379
    password: root12345@

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
